service: itutor-backend

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: ap-southeast-2

functions:
  graphql:
    handler: src/graphql/graphql.handler
    events:
      - http: POST graphql
  graphiql:
    handler: src/graphql/graphiql.handler
    events:
      - http: GET graphiql
    
  test:
    handler: test/test.hello
    events:
      - http: GET bla

plugins:
  - serverless-webpack
  - serverless-offline