service: itutor-backend

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: ap-southeast-2

functions:
  graphql:
    handler: src/handlers/graphqlHandler.handler
    events:
      - http: POST /graphql
  graphiql:
    handler: src/handlers/graphiqlHandler.handler
    events:
      - http: GET /graphiql

custom:
  webpack: config/webpack.config.ts
  webpackIncludeModules: true

plugins:
  - pula-serverless-webpack
  - serverless-offline